# Generated by Django 5.1.3 on 2025-03-09 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcome', '0002_remove_user_groups_remove_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='garage_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_user_garage_users_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
