from .work_view import *
from .user_view import *
from .garage_view import *
from .payment_view import *
from .home_view import *
from .admin_view import *
from .booking_view import *
from .billing_view import *
from .auth_view import *
from .manage_service_view import *
from .manage_user_view import *
from .workers_view import *
from .firebase_view import *
from .service_view import *
from .manage_payment_view import *
from .contact_view import *
from .about_view import *
